GET https://streaming-graph.facebook.com/4014543378605925/live_comments?access_token=EAAeKlDx3HnsBABmUCJCjVZBIYeAi1xZCLQKeNQn3ekUZAQWZCni3sZBb1dtiyYXdHLKHKpFzGju3S1bFpGNO3IogrIP1Qcw0Uror4ngYPD5sV9IvZCkCrbNUZAyBEvZCgU4T5QlKmWQFPXdg3CJXxrqlXMDkbZCl2orsmE6ffeJYA5u5LsqXtnGUZAArPJOQn9EH1p3UTC0V69TsFe78kwbmwZBADf04k0NkPvcQYAhgW2vSLliKDju1NNA&comment_rate=one_per_two_seconds&fields=from{name,id},message 